# Generated by Django 5.2.17 on 2026-08-26 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_slug', models.SlugField(help_text='Identifies which page this section belongs to (e.g. "home").')),
                ('section_key', models.CharField(help_text='Identifies the section within the page (e.g. "hero").', max_length=100)),
                ('heading', models.CharField(max_length=255)),
                ('paragraph', models.TextField()),
                ('image', models.ImageField(blank=True, help_text='Optional. Leave empty for text-only sections.', null=True, upload_to='sections/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'page section',
                'verbose_name_plural': 'page sections',
                'ordering': ['page_slug', 'section_key'],
                'unique_together': {('page_slug', 'section_key')},
            },
        ),
    ]
