# Generated by Django 5.2.17 on 2026-08-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesection',
            name='heading',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='paragraph',
            field=models.TextField(null=True),
        ),
    ]
