# Generated by Django 5.2.17 on 2026-08-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_pagesection_heading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesection',
            name='heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='paragraph',
            field=models.TextField(blank=True, null=True),
        ),
    ]
