# Generated by Django 5.2.17 on 2026-08-30 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_pagesection_heading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesection',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional. Leave empty for text-only sections.', max_length=500, null=True, upload_to='sections/'),
        ),
    ]
